### ISSUE TITLE
No package metadata was found for bitsandbytes

### ISSUE THREAD

**Issue by ziziguai** [huchenlei/ComfyUI_omost#10]
![image](https://github.com/huchenlei/ComfyUI_omost/assets/12597310/98ee6665-01ee-485c-9082-6c87f4fa0e43)
![image](https://github.com/huchenlei/ComfyUI_omost/assets/12597310/8ce96414-c942-4abe-a0c8-870cfd5e2ce6)
是transformers版本问题吗？

**Comment by StefanoMartin** [comment]
Personally I solved my doing the following:
* Click on "Manager"
* Click on "Install PIP Packages"
* In the input write "bitsandbytes"
* Restart to install the missing library

**Comment by huchenlei** [comment]
Sorry I missed that dep. Deps updated in https://github.com/huchenlei/ComfyUI_omost/commit/1c367e6dd690a35e7ba681ae7c61409ae42abb8b.

**Comment by ziziguai** [comment]
ok, pip install bitsandbytes 
can solve
