### ISSUE TITLE
为啥我第三个节点和你的不一样

### ISSUE THREAD

**Issue by linjian-ufo** [huchenlei/ComfyUI_omost#2]
我的是OmostRenderCanvasConditioningNode
你的是Omost Canvas Render

**Comment by linjian-ufo** [comment]
Error occurred when executing OmostLLMLoaderNode:

(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /lllyasviel/omost-llama-3-8b-4bits/resolve/main/config.json (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)')))"), '

**Comment by huchenlei** [comment]
This node pack is still WIP. Things are subject to change. I will change the screenshot in the readme later.
