### ISSUE TITLE
这个节点后面会考虑加入多轮对话编辑图片吗？

### ISSUE THREAD

**Issue by lianghuoyou** [huchenlei/ComfyUI_omost#29]
亲爱的作者你好，我昨天试了一下，好像还不能进行多轮对话进行编辑图片，试了好几次都只是作用于第一次对话，后面会考虑加上这个功能吗？

**Comment by huchenlei** [comment]
![image](https://github.com/huchenlei/ComfyUI_omost/assets/20929282/3fc94564-9213-41d2-959a-453dfe8ee681)
