### ISSUE TITLE
whats the role of "omost greedy bags text embedding " node in comfyui?

### ISSUE THREAD

**Issue by yatoubusha** [huchenlei/ComfyUI_omost#39]
whats the role of "omost greedy bags text embedding " node in comfyui?
![image](https://github.com/huchenlei/ComfyUI_omost/assets/34413340/1ed874a0-7b63-41c0-a2bf-cb4b39ca6099)

**Comment by huchenlei** [comment]
It is just OmostDenseDiffusion node without the region condition. See https://github.com/huchenlei/ComfyUI_omost/pull/27
