### ISSUE TITLE
Error running "Omost LLM Loader"

### ISSUE THREAD

**Issue by xiao-ning-ning** [huchenlei/ComfyUI_omost#5]
Error occurred when executing OmostLLMLoaderNode:

LlamaForCausalLM.__init__() got an unexpected keyword argument 'token'

File "C:\AI\ComfyUI-aki-v1.1\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "C:\AI\ComfyUI-aki-v1.1\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "C:\AI\ComfyUI-aki-v1.1\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "C:\AI\ComfyUI-aki-v1.1\custom_nodes\ComfyUI_omost\omost_nodes.py", line 99, in load_llm
llm_model = AutoModelForCausalLM.from_pretrained(
File "C:\AI\ComfyUI-aki-v1.1\python\lib\site-packages\transformers\models\auto\auto_factory.py", line 484, in from_pretrained
return model_class.from_pretrained(
File "C:\AI\ComfyUI-aki-v1.1\python\lib\site-packages\transformers\modeling_utils.py", line 2675, in from_pretrained
model = cls(config, *model_args, **model_kwargs)
![PixPin_2024-06-05_09-55-41](https://github.com/huchenlei/ComfyUI_omost/assets/135084846/7ad4df8b-608f-440a-9a88-169b2076e301)

**Comment by huchenlei** [comment]
Please verify you have python pip requirements satisfied:
https://github.com/huchenlei/ComfyUI_omost/blob/c8f12b21df5ffee9dc0838018382a42409308bc7/requirements.txt#L1

**Comment by xiao-ning-ning** [comment]
Thank you for your prompt reply! I installed all the dependencies of Omost, but the error still exists.
![Uploading PixPin_2024-06-05_10-16-41.jpg…]()

**Comment by xiao-ning-ning** [comment]
[SD-Launcher] C:\AI\ComfyUI-aki-v1.1>pip show transformers
Name: transformers
Version: 4.41.1
Summary: State-of-the-art Machine Learning for JAX, PyTorch and TensorFlow
Home-page: https://github.com/huggingface/transformers
Author: The Hugging Face team (past and future) with the help of all our contributors (https://github.com/huggingface/transformers/graphs/contributors)
Author-email: transformers@huggingface.co
License: Apache 2.0 License
Location: c:\users\admin\appdata\local\programs\python\python310\lib\site-packages
Requires: filelock, huggingface-hub, numpy, packaging, pyyaml, regex, requests, safetensors, tokenizers, tqdm
Required-by: peft, sentence-transformers, streamdiffusion, transformers-stream-generator, unstructured-inference

[SD-Launcher] C:\AI\ComfyUI-aki-v1.1>pip show torch
Name: torch
Version: 2.1.0
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: c:\users\admin\appdata\local\programs\python\python310\lib\site-packages
Requires: filelock, fsspec, jinja2, networkx, sympy, typing-extensions
Required-by: accelerate, bitsandbytes, effdet, openai-whisper, peft, pytorch-lightning, sentence-transformers, timm, torchaudio, torchmetrics, torchsde, torchvision, xformers

**Comment by FLYleoYBQ** [comment]
我似乎没办法安装transformers>=4.41.1

**Comment by xiao-ning-ning** [comment]
I can run the node smoothly now.
I have installed the following dependencies:
transformers==4.41.1
bitsandbytes==0.43.1
torch==2.3.0

Now running perfectly！
